# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:alpine
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  
stages:
  - build
  - deploy

build:
  image: node:alpine
  stage: build
  tags: 
    - builder
    
  script:
   - npm install -g cnpm --registry=https://registry.npm.taobao.org
   - cnpm -v
   - cnpm install wepy-cli -g
   - cnpm install
   - cnpm run build
   
  artifacts:
    expire_in: 1 week
    paths:
      - dist


deploy_master:
  image: alpine
  stage: deploy
  only:
    - master
  tags: 
    - builder
  script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ ider@192.168.1.223:/home/ider/docker-compose/nginx/www/wiki.knogen.com
    - echo "$SSH_PRIVATE_KEY_TOP" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - rsync -rav -e 'ssh -p 579' --delete dist/ www-data@114.55.237.247:/var/www/wiki.knogen.com



